### ISSUE TITLE
Cannot build the latest bump

### ISSUE THREAD

**Issue by HaFred** [sequencer/rocket-playground#2]
Hi @sequencer , I have checkout the latest bump with `git submodule update --init` and tried to build the env. But it failed as below:
```
~/testsocket/design/craft/fpga-test-socket/src/Configs.scala:21:8
not found: value PeripheryMaskROMKey
  case PeripheryMaskROMKey => List(
```

**Comment by sequencer** [comment]
yep testsocket are a little staled, I should remove it.
